<a href="https://colab.research.google.com/github/Taka0007/2023-seminar-previous.term/blob/main/code/%E9%9F%B3%E5%A3%B0%E5%88%86%E9%9B%A2NMF%E5%AE%9F%E8%A3%85%E7%94%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# import
import pandas as pd
import numpy as np
import librosa
import librosa.display
import matplotlib.pyplot as plt
from numpy import linalg as LA
from sklearn.decomposition import NMF

In [8]:
# wavファイルDL
!wget https://github.com/Taka0007/2023-seminar-previous.term/raw/main/wav-files/aiueo.wav -O aiueo.wav
file_path = '/content/aiueo.wav'
audio_data, sr = librosa.load(file_path)

--2023-06-20 08:00:20--  https://github.com/Taka0007/2023-seminar-previous.term/raw/main/wav-files/aiueo.wav
Resolving github.com (github.com)... 140.82.112.4
Connecting to github.com (github.com)|140.82.112.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/Taka0007/2023-seminar-previous.term/main/wav-files/aiueo.wav [following]
--2023-06-20 08:00:20--  https://raw.githubusercontent.com/Taka0007/2023-seminar-previous.term/main/wav-files/aiueo.wav
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 32832 (32K) [audio/wav]
Saving to: ‘aiueo.wav’

aiueo.wav           100%[===================>]  32.06K  --.-KB/s    in 0.002s  

2023-06-20 08:00:20 (15.0 MB/s) - ‘aiueo.wav’ saved [32832/32832]



<ipython-input-8-0da643ce9416>:4: UserWarning: PySoundFile failed. Trying audioread instead.
  audio_data, sr = librosa.load(file_path)
/usr/local/lib/python3.10/dist-packages/librosa/core/audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)


In [20]:
#高速フーリエ変換
fft_spec = np.fft.rfft(audio_data)

# NMFを行うために、fft_specを2次元配列に変換
fft_spec = fft_spec.reshape(len(fft_spec),1)
print(fft_spec)

[[-2.78108568e+01+0.00000000e+00j]
 [-4.17856923e+00+1.67983792e+01j]
 [ 2.63063313e+01+1.49804326e+01j]
 ...
 [ 6.29508110e-03-1.11692273e-06j]
 [ 6.29458866e-03+2.31351483e-06j]
 [ 6.29570565e-03-2.41347811e-07j]]


In [21]:
type(fft_spec)

numpy.ndarray

In [22]:
print(fft_spec)
print(fft_spec.shape)

[[-2.78108568e+01+0.00000000e+00j]
 [-4.17856923e+00+1.67983792e+01j]
 [ 2.63063313e+01+1.49804326e+01j]
 ...
 [ 6.29508110e-03-1.11692273e-06j]
 [ 6.29458866e-03+2.31351483e-06j]
 [ 6.29570565e-03-2.41347811e-07j]]
(54905, 1)


In [24]:
# 複素NMFの実装
def complex_nmf(V, rank, num_iterations):
    # 行列のサイズを取得
    n, m = V.shape

    # WとHの初期化
    W = np.random.rand(n, rank)
    H = np.random.rand(rank, m)

    # 反復更新
    for i in range(num_iterations):
        # Wの更新
        numerator_W = np.abs(V) @ H.T
        denominator_W = W @ H @ H.T
        W *= numerator_W / (denominator_W + 1e-9)

        # Hの更新
        numerator_H = W.T @ np.abs(V)
        denominator_H = W.T @ W @ H
        H *= numerator_H / (denominator_H + 1e-9)

    return W, H

rank = np.linalg.matrix_rank(fft_spec)
W, H = complex_nmf(fft_spec, rank, num_iterations=100)
Ans = W @ H
# 結果の表示
print("W:")
print(W)

print("H:")
print(H)

print('fft_spec')
print(fft_spec)

print('Ans')
print(Ans)


W:
[[1.29850093e+02]
 [8.08224713e+01]
 [1.41344550e+02]
 ...
 [2.93919845e-02]
 [2.93896868e-02]
 [2.93949001e-02]]
H:
[[0.21417664]]
fft_spec
[[-2.78108568e+01+0.00000000e+00j]
 [-4.17856923e+00+1.67983792e+01j]
 [ 2.63063313e+01+1.49804326e+01j]
 ...
 [ 6.29508110e-03-1.11692273e-06j]
 [ 6.29458866e-03+2.31351483e-06j]
 [ 6.29570565e-03-2.41347811e-07j]]
Ans
[[2.78108568e+01]
 [1.73102855e+01]
 [3.02727010e+01]
 ...
 [6.29507653e-03]
 [6.29458441e-03]
 [6.29570099e-03]]


## いらないやつ

In [ ]:
#非負値行列因子分解(NMF)の実行

class NMF:
  """
  非負値行列因子分解を行う
  X を H,Uの2行列に分解する
  HUがXに近づくように近似を行う

  Attributes
    --------
    __init__:None
      行列の初期値策定・精度指定などを行う

    need_opt:bool
      Y-HUのノルムが精度以内に収まっているか確認。
      ここがTrueなら更新を続ける

    update:

    """
  def __init__(self, X : np.array)-> None:
    # 元の行列を代入
    self.X = X

    # 精度を指定(誤差をどれくらいまで許容するか)
    self.acc = 0.1

    #行列の列数と行数を取得
    self.numRows = X.shape[0]
    self.numColumns = X.shape[1]

    #分解後の行列の初期値策定 (0,1をランダムに分布させた行列)
    self.H = np.random.randint(0,1,(self.numRows,1))
    self.U = np.random.randint(0,1,(1,self.numColumns))

  # 更新を続けるか否か
  def need_opt(self) -> bool:

    # X-HU行列
    self.judge = self.X - self.H @ self.U

    # X-HUのノルムが、基準値を超えている（条件を満たしていない）なら更新を続ける
    if LA.norm(self.judge,"fro") >= self.acc:
      return True
    else:
      return False


  def update(self) -> None:
    self.H = self.H *

  def solve(self) -> np.array:

    while self.is_opt():
      self.update


In [7]:


# テストデータの作成
n = 10
m = 8
rank = 3
V = np.random.rand(n, m) + 1j * np.random.rand(n, m)

# 複素NMFの実行
W, H = complex_nmf(V, rank, num_iterations=100)
Ans = W @ H
# 結果の表示
print("W:")
print(W)

print("H:")
print(H)

print('V')
print(V)

print('Ans')
print(Ans)

W:
[[4.60234494e-01 7.07096478e-02 5.43919124e-01]
 [7.15295454e-01 4.18562198e-01 1.97205819e-01]
 [7.37573522e-01 5.46081173e-01 2.52199070e-02]
 [3.24518413e-04 6.77842987e-01 5.50253317e-01]
 [9.41020773e-02 3.54494973e-01 8.82528774e-01]
 [3.59417671e-01 8.08843991e-03 7.78030769e-01]
 [6.96731383e-01 2.01720996e-01 3.29360342e-01]
 [9.97408244e-02 1.02994446e+00 1.83991273e-01]
 [1.45675933e-01 5.21425506e-01 4.33288082e-01]
 [6.79668206e-01 3.86374285e-01 2.68102677e-01]]
H:
[[0.427691   0.00255128 0.78485578 1.11481246 0.46715145 0.47330723
  0.91430971 0.7236464 ]
 [0.71118857 1.2223693  0.02705469 0.613723   0.42830608 0.57867834
  0.83659318 0.94052433]
 [0.59345522 0.42771051 1.30258761 0.05538791 0.88500753 0.82385675
  0.27478358 0.06377027]]
V
[[0.08338938+0.21946722j 0.32939412+0.2679432j  0.93451726+0.26966338j
  0.15622739+0.70225422j 0.99743858+0.40025857j 0.17964067+0.65503548j
  0.49065981+0.37850411j 0.33110462+0.06577626j]
 [0.28119947+0.63945285j 0.2490646 +0.43